backend:
  name: github
  branch: main
  repo: erichieule/documentations
  commit_messages:
    create: doc:create {{collection}} by {{author-name}} at “{{slug}}”
    update: doc:update {{collection}} by {{author-name}} at “{{slug}}”
    delete: doc:delete {{collection}} by {{author-name}} at “{{slug}}”
    uploadMedia: doc:upload image “{{path}}”
    deleteMedia: doc:delete image “{{path}}”

publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
site_url: https://documentations-rho.vercel.app/

collections:
  - name: "docs"
    label: "Docs"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
