backend:
  # name: github
  # branch: main
  # repo: erichieule/documentations
  name: git-gateway

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: docs
    label: "Docs"
    folder: docs
    create: true
    slug: "{{slug}}"
    identifier_field: title
    extension: md
    widget: "list"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
